export const CONNECT = "APP/CONNECT";
export const CREATE_MESSAGE_STREAM = "APP/CREATE_MESSAGE_STREAM";
export const CREATE_USER = "APP/CREATE_USER";
export const RECEIVE_MESSAGE = "APP/RECEIVE_MESSAGE";
export const SET_USER_LIST = "APP/SET_USER_LIST";
export const GET_COMMON_MESSAGES = "APP/GET_COMMON_MESSAGES";
export const GET_DIRECT_MESSAGES = "APP/GET_DIRECT_MESSAGES";