export const CONNECT = "APP/CONNECT";
export const CREATE_MESSAGE_STREAM = "APP/CREATE_MESSAGE_STREAM";
export const MESSAGE_SEND = "APP/MESSAGE_SEND";
export const CREATE_USER = "APP/CREATE_USER";
export const RECEIVE_MESSAGE = "APP/RECEIVE_MESSAGE";